"""add users and posts

Revision ID: cc6abb66bed0
Revises: 
Create Date: 2019-02-28 19:01:02.098927

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'cc6abb66bed0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=100), nullable=False),
                    sa.Column('password', sa.String(length=100), nullable=False),
                    sa.Column('create_time', sa.DateTime(), nullable=True),
                    sa.Column('is_local', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('image_url', sa.String(length=200), nullable=False),
                    sa.Column('thumb_url', sa.String(length=200), nullable=False),
                    sa.Column('upload_time', sa.DateTime(), nullable=True),
                    sa.Column('is_delete', sa.Boolean(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('users')
    # ### end Alembic commands ###
