"""add two field for posts

Revision ID: ef1b30c3c62f
Revises: cc6abb66bed0
Create Date: 2019-02-28 19:50:28.655290

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ef1b30c3c62f'
down_revision = 'cc6abb66bed0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('good_num', sa.Integer(), nullable=False))
    op.add_column('posts', sa.Column('like_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'like_num')
    op.drop_column('posts', 'good_num')
    # ### end Alembic commands ###
